AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Gemenie Labs Contact Form API

Parameters:
  ToEmail:
    Type: String
    Description: Email address to receive contact form submissions
    Default: contact@gemenielabs.com
  FromEmail:
    Type: String
    Description: Verified SES email to send from
    Default: noreply@gemenielabs.com

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13
    MemorySize: 128

Resources:
  ContactApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"

  ContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: contact.handler
      Environment:
        Variables:
          TO_EMAIL: !Ref ToEmail
          FROM_EMAIL: !Ref FromEmail
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
      Events:
        Contact:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /contact
            Method: POST

Outputs:
  ContactApiUrl:
    Description: Contact form API URL
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/prod/contact"
